
=head1 NAME

umph - Command line tool for parsing YouTube feeds

=head1 SYNOPSIS

umph [-q] [-i] [-a] [--csv | --json] [-t E<lt>typeE<gt>]
     [--proxy E<lt>addrE<gt>| --no-proxy]
     [E<lt>playlist_idE<gt> | E<lt>usernameE<gt>]

=head1 DESCRIPTION

umph is a command line tool for parsing YouTube feeds. It can parse
playlists, favorite lists, and user upload lists.

umph prints the found URLs to the standard output, each URL separated
with a newline. It can be used to select the feed items using the
C<--interactive> prompt.

=head1 OPTIONS

=over 4

=item B<-h, --help>

Print help and exit.

=item B<-v, --version>

Print version and exit.

=item B<-q, --quiet>

Turn off output to stderr, e.g. status changes. Warnings and errors are
still printed.

=item B<-t, --type> I<arg> (=p)

Specifies the feed type to get. I<arg> can be one of the following:

 p, playlist  (arg0 will be treated as playlist ID)
 f, favorites (arg0 will be treated as username)
 u, uploads   (ditto)

See also L</EXAMPLES>.

=item B<-s, --start-index> I<arg> (=1)

"The start-index parameter specifies the index of the first matching result
that should be included in the result set. This parameter uses a one-based
index, meaning the first result is 1, the second result is 2 and so forth.

This parameter works in conjunction with the C<--max-results> parameter to
determine which results to return. For example, to request the second set
of 10 results, i.e. results 11-20, set the start-index parameter to 11
and the max-results parameter to 10." -- E<lt>http://is.gd/l4wDNfE<gt>

C<--all> causes umph to ignore the value set with this option.

=item B<-m, --max-results> I<arg> (=25)

"The max-results parameter specifies the maximum number of results that
should be included in the result set.

This parameter works in conjunction with the C<--start-index>  parameter
to determine which results to return. For example, to request the second
set of 10 results, i.e. results 11-20, set the max-results parameter
to 10 and the start-index parameter to 11.

The default value of this parameter is 25, and the maximum value is 50.
However, for displaying lists of videos, we recommend that you set the
max-results parameter to 10." -- E<lt>http://is.gd/OcSjwUE<gt>

C<--all> causes umph to ignore the value set with this option.

=item B<-a, --all>

Get all feed items.

=item B<-i, --interactive>

Use interactive prompt which can be used to select the feed items.
+umph selects I<all> feed items by default.

=item B<--json>

Print details in JSON. Negates --csv.

=item B<--csv>

Print details in CSV ("$title","$url"\n).

=item B<--proxy> I<arg>

Use I<arg> for HTTP proxy, e.g. "http://foo:1234". Overrides the http_proxy
environment setting.

=item B<--no-proxy>

Disable use of HTTP proxy. Overrides both C<--proxy> and http_proxy environment
settings.

=back

=head1 EXAMPLES

=head2 umph AAF3A1D0CA1E304F

Get playlist "AAF3A1D0CA1E304F".

=head2 umph --json AAF3A1D0CA1E304F

Same as above, but print the details in JSON.

=head2 umph -s 11 -m 10 AAF3A1D0CA1E304F

Same as above but get the items 11-20 from the playlist.

=head2 umph -a AAF3A1D0CA1E304F

Similar but get I<all> of the items in the playlist. By default, umph gets
only the items 1-25 from the list. See also C<--start-index> and
C<--max-results>.

=head2 umph -t f foo

Get favorites for user "foo".

=head2 umph -t u foo

Get uploads for user "foo".

=head2 umph AAF3A1D0CA1E304F | cclive

Download the found items with C<cclive(1)>.

=head1 EXIT STATUS

Exits 0 on success, otherwise 1.

=head1 FILES

=head2 ~/.umphrc

=head3 Example:

 echo "--interactive" >> ~/.umphrc

=head1 NOTES

=over 4

=item B<http_proxy>

umph depends on XML::DOM which uses LWP::UserAgent to fetch the data
over the network. LWP::UserAgent reads the http_proxy environment
setting. e.g.:

 env http_proxy=http://foo:1234 umph AAF3A1D0CA1E304F

=item B<Unavailable feeds>

umph cannot parse "private" lists.

=back

=head1 WWW

 Home  : <http://umph.googlecode.com/>
 gitweb: <http://repo.or.cz/w/umph.git>

=head1 LICENSE

umph is free software, licensed under the GPLv3+.

=head1 SEE ALSO

C<cclive(1)>

=head1 AUTHOR

Toni Gundogdu <legatvs at sign cpan org>
